<a href="https://colab.research.google.com/github/fidanfatih/Pycoders_Capstone/blob/main/week_1_Semih.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [4]:
# !pip install numpy

In [5]:
import numpy as np 

In [6]:
#ornek-1
#Normal yollardan listenin her elemanini birbiri ile carpalim.

a = [1,2,3,4]
b = [2,3,4,5]

In [7]:
a = [1,2,3,4]
b = [2,3,4,5]

ab=[]                     

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [8]:
# Ayni islemi hatta daha fazlasini Numpy ile yapalim.

a = np.array([1,2,3,4])

b = np.array([2,3,4,5])

c = np.array([5,6,3,0])

a * b * c    # iki veriyi indexli carpma islemi yapar

array([10, 36, 36,  0])

In [9]:
#ornek-2 her listenin son elemanlarina ulasin. ilkel yontem
a = [[1,23,4],
     [5,6,7],
     [89,9,99]]
liste = []

for i in range(len(a)):
    liste.append(a[i][2])

print(liste)


[4, 7, 99]


In [10]:
# Numpy ile  her listenin son elemanlarina ulasin. 
a = np.array([[1,23,4],
              [5,6,7],
              [89,9,99]])

a[:,-1]  #son sutundaki elemanlara ulasir

array([ 4,  7, 99])

In [11]:
# ornek-3 butun elemanlari 5 ile carpma
a = np.array([[1,23,4],
              [5,6,7],
              [89,9,99]])
a*5

array([[  5, 115,  20],
       [ 25,  30,  35],
       [445,  45, 495]])

# NumPy Arrayleri Oluşturma

### Listelerden Array Oluşturmak

In [12]:
import numpy as np 

a = np.array([12,33,4,5])  # tekboyutlu
a


array([12, 33,  4,  5])

In [13]:
type(a)

numpy.ndarray

In [14]:
# numpy array olusturma bu sekilde olur > np.array([....])

a = np.array([3.14, 4, 6, 1.2])
a 

#ciktida hepsi float oldu.

array([3.14, 4.  , 6.  , 1.2 ])

In [15]:
#tipini degistirme

np.array([3.14, 4, 6.,2], dtype = 'float32')    # icerisindeki tum elemanlarin type float32 yapar yada int32

array([3.14, 4.  , 6.  , 2.  ], dtype=float32)

In [16]:
#sifirlardan array olusturma

np.zeros((5,3), dtype = 'int32')    # sadece sifirlardan olusan 5 x 3 lu int veri array olusturur dtype default floattur


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [17]:
# Birlerden array olusturma

np.ones((2,3))  # sadece 1 lerden  olusan 2x3 (matris) int veri arrayi olusturur.

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#istedigimiz degerden array olusturma

np.full((6,7),9)         # 6 ye 7 lik matrislerden icinde 9 olan array olusturur

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [19]:
np.arange(0,10,2)     # 0 dan 10 kadar 2ser 2ser giden bir array olusturur, tek boyutlu son dizin dahil degil

array([0, 2, 4, 6, 8])

In [20]:
np.linspace(-1,1,30)   # -1 ile 1 arasinda 30 adet dizi olusturur.  bolumu 30'a boler ve ondalikli sayilar olusturur

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [21]:
np.random.randint(0,10, (2,2))     # 0 ile 10 arasinda integerlardan olusan 2 ye 2lik bir matris olusturur. Degerler rastgele secilir. 

array([[8, 0],
       [9, 4]])

In [22]:
np.eye(5)        # 5x5lik kosegenleri 1 olan bir matris olusturur, eyedentidi matris

                 # buna  DIAGONAL / birim matris de denir.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Numpy Biçimlendirme

* **ndim**: boyut sayısı

* **shape**: satir ve sutun bilgisini verir, kaclik matris

* **size**: toplam eleman sayısı

* **dtype**: array veri tipi

In [23]:
import numpy as np

a = np.random.randint(6, size =10)   # 0 dan 6'a kadar random size = 10 adet veri olusturur, 
a

array([3, 4, 5, 2, 5, 3, 2, 5, 1, 5])

In [24]:
print("Boyut sayisi =  ",a.ndim) 
print("satir, sutun bilgisi =  ",a.shape)  #BOYUT BILGISI ? 
print("Toplam eleman sayisi =  ",a.size)
print("Veri tipi =  ",a.dtype)

Boyut sayisi =   1
satir, sutun bilgisi =   (10,)
Toplam eleman sayisi =   10
Veri tipi =   int64


In [25]:
a = np.random.randint(10, size = (10, 5))
a

array([[2, 5, 4, 7, 2],
       [4, 1, 4, 3, 7],
       [9, 2, 9, 5, 7],
       [8, 1, 6, 4, 2],
       [8, 0, 5, 9, 3],
       [8, 6, 8, 5, 6],
       [9, 2, 7, 7, 3],
       [1, 0, 2, 0, 4],
       [3, 4, 2, 0, 0],
       [2, 8, 9, 5, 4]])

In [26]:
a.ndim #Boyut sayisi

2

In [27]:
a.shape # satir sutun

(10, 5)

In [28]:
a.size   #eleman sayisi

50

In [29]:
a.dtype   # veri type

dtype('int64')

In [30]:
a = np.random.randint(10, size = (2,4,7))   # 2 TANE 3 boyutlu array (adet, satir, sutun)

a

array([[[3, 3, 2, 0, 6, 2, 1],
        [4, 7, 9, 5, 3, 0, 6],
        [9, 9, 1, 9, 3, 7, 8],
        [1, 5, 3, 5, 4, 8, 9]],

       [[1, 7, 2, 4, 0, 0, 8],
        [2, 9, 0, 3, 5, 2, 9],
        [5, 3, 6, 1, 5, 0, 8],
        [9, 5, 9, 9, 4, 1, 8]]])

In [31]:
a.ndim

3

In [32]:
a.shape

(2, 4, 7)

In [33]:
a.size

56

In [34]:
a.dtype

dtype('int64')

In [35]:
np.arange(1,10)   # 1 den 10 a kadar tek boyutlu array olusturur.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#vektorleri matrise cevirme

np.arange(1,10).reshape(3,3)   # tek bouyutlu arrayi, 3 boyutlu matrise cevirdik. 3x3=9 adet eleman olmak zorunda


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a = np.array([1,2,3,5,6,7,8,9,0])        #tek boyutlu array,

In [38]:
a

array([1, 2, 3, 5, 6, 7, 8, 9, 0])

In [39]:
b = a.reshape((3,3))   # tek boyutlu arrayi 3e 3luk matrise cevirdik   3x3 = 9 adet eleman olmak zorunda
b

 # Not = [[]] demek 2 boyutlu demek, [] tek boyutlu demek

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [40]:
b.ndim   # boyut sayisi

2

In [41]:
a.ndim

1

## birlestirme islemleri

In [42]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [43]:
x

array([1, 2, 3])

In [44]:
y

array([4, 5, 6])

In [45]:
np.concatenate([x,y])   # iki arrayi birlestirme islemi yapar []

array([1, 2, 3, 4, 5, 6])

In [46]:
z = [1,2,3]

In [47]:
np.concatenate([x,y,z])   # 3 arrayi birlestirdi

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [48]:
#iki boyutlu

In [49]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [51]:
np.concatenate([a,a], axis = 1)   # birlestirme islemini yatay (sutun) olarak yapar  1 sutun, 0satir

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [52]:
#farklı boyutlu  vektor ve matrisleri birlestirme

In [53]:
a = np.array([1, 2, 3])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])

In [54]:
a #  tek boyutlu

array([1, 2, 3])

In [55]:
b  # iki boyutlu

array([[9, 8, 7],
       [6, 5, 4]])

In [56]:
np.vstack([a,b])   # farkli boyutlu arraylari SATIR BAZLI birlestirme yapar

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [57]:
a = np.array([[99],
              [99]])

b = np.array([[9, 8, 7], 
              [6, 5, 4]])

In [58]:
np.hstack([a,b])   # yatay SUTUN BAZLI bir sekilde birlestirme yapar,

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

## array ayirma splitting

In [59]:
x = [1, 2, 3, 99, 99, 3, 2, 1,33,4,567,112,4678,33]
x

[1, 2, 3, 99, 99, 3, 2, 1, 33, 4, 567, 112, 4678, 33]

In [60]:
np.split(x, [3,6,9])  

# x i 4 parcaya bolecek ve ilkini 3.indexten bolecek, sonra 6.indexten bolecek, sonra 9 dan bolecek 
#cikan sonuclar array type olacak.

[array([1, 2, 3]),
 array([99, 99,  3]),
 array([ 2,  1, 33]),
 array([   4,  567,  112, 4678,   33])]

In [61]:
a,b,c,d = np.split(x, [3,6,9])   # bolunme isleminde olusan arraylari sirasiyla a b c d ye atadik

In [62]:
print(a,b,c,d)

[1 2 3] [99 99  3] [ 2  1 33] [   4  567  112 4678   33]


##  array siralama 

In [63]:
import numpy as np
v = np.array([2, 1, 4, 3, 5])
v

array([2, 1, 4, 3, 5])

In [64]:
np.sort(v)   # kucukten siralama yapar ama ana veriyi bozmaz

array([1, 2, 3, 4, 5])

In [65]:
v

array([2, 1, 4, 3, 5])

In [66]:
v.sort()  # kucukten siralama yapar ama ana veri bozulur. bu yuzden tercih edilmez

In [67]:
v

array([1, 2, 3, 4, 5])

# NumPy Eleman İşlemleri

## Index ile Elemanlara Erişmek

In [68]:
import numpy as np
a = np.random.randint(10, size = 10)    # 0 dan 10 akadar random size = 10 adet veri olusturur, 
a

array([5, 3, 1, 2, 8, 7, 1, 5, 0, 6])

In [69]:
a[0]   # a nin 0.indexine (ilk elemana ) ulasir

5

In [70]:
a[-2]   # tersten 2. elemana ulasir 

0

In [71]:
a[0] = 1  # a nin  0. indexindeki elemani degistirdik. 1 yaptik

In [72]:
a

array([1, 3, 1, 2, 8, 7, 1, 5, 0, 6])

In [73]:
a = np.random.randint(10, size = (3, 5))   #3x5 iki boyutlu matris
a

array([[2, 4, 6, 2, 8],
       [0, 7, 9, 1, 8],
       [6, 4, 8, 1, 1]])

In [74]:
a[1,1]   # iki boyutlu elamanlara eristik. 1. satir ve 1.sutundaki elemana ulasir

7

In [75]:
a[1,3]   # 1.satir, 3.sutun

1

In [76]:
a[0,0] = 1  # 0.satir ve 0.sutundaki elemani degistir. 1 yap

In [77]:
a[0,0]

1

In [78]:
a[0,0] = 2.2   #array int oldugu icin flout bile gondersek o integer olarak atayacak. 

In [79]:
a[0,0] 

2

## Slicing ile Array Alt Kümesine Erişmek

In [80]:
import numpy as np
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [81]:
a[0:3]   # 0dan 3 e kadar elemanlari  alir (index olarak)

array([20, 21, 22])

In [82]:
a[:3]    # en bastan 3. indexe kadar alir

array([20, 21, 22])

In [83]:
a[3:]  # 3.indexten sonuna kadar alir

array([23, 24, 25, 26, 27, 28, 29])

In [84]:
a[::2]   # en bastan baslar en sona kadar 2ser 2ser atlayarak gider

array([20, 22, 24, 26, 28])

In [85]:
a[1::2]     # 1.indexten baslar sonuna kadar gider  2ser 2ser atlayarak gider

array([21, 23, 25, 27, 29])

In [86]:
a[2::2]    # 2.indexten baslar sonuna kadar gider  2ser 2ser atlayarak gider

array([22, 24, 26, 28])

In [87]:
a[1::3]     # 1.indexten baslar sonuna kadar gider  3ser 3ser atlayarak gider

array([21, 24, 27])

In [88]:
a = np.random.randint(10, size = (5, 5))
a

array([[3, 6, 7, 7, 8],
       [7, 1, 5, 5, 5],
       [6, 6, 2, 9, 8],
       [4, 3, 7, 8, 8],
       [4, 9, 3, 9, 8]])

In [89]:
a[:,0]    
# 0.sutunun tum satirlarini secer

array([3, 7, 6, 4, 4])

In [90]:
a[:,1]   # 1.sutunun tum satirlarini secer

array([6, 1, 6, 3, 9])

In [91]:
a[:,4]   # 4.sutunun tum satirlarini secer

array([8, 5, 8, 8, 8])

In [92]:
a

array([[3, 6, 7, 7, 8],
       [7, 1, 5, 5, 5],
       [6, 6, 2, 9, 8],
       [4, 3, 7, 8, 8],
       [4, 9, 3, 9, 8]])

In [93]:
a[4,:]   # tum sutunlarin 4.satirini alir

array([4, 9, 3, 9, 8])

In [94]:
a[0]  # 0.satirin tum sunutlarini verir. Ilk satirin tamami

array([3, 6, 7, 7, 8])

In [95]:
a[1]  # 1.satirin tum sunutlarini verir. ikinci  satirin tamami

array([7, 1, 5, 5, 5])

In [96]:
a[2]  # 2.satirin tum sutunlarini verir. ucuncu satirin tamami

array([6, 6, 2, 9, 8])

In [97]:
a[:2,:3]   # 0dan 2 yekadar olan satirlarin : 0dan 3 e kadar olan sutunlari secer   son degerler dahil degil

array([[3, 6, 7],
       [7, 1, 5]])

In [98]:
a[0:2,0:3]  # 0dan 2 yekadar olan satirlarin : 0dan 3 e kadar olan sutunlari secer   son degerler dahil degil

array([[3, 6, 7],
       [7, 1, 5]])

In [99]:
a[:,:2]     # tum satirlarin ilk iki sutununu secti

array([[3, 6],
       [7, 1],
       [6, 6],
       [4, 3],
       [4, 9]])

In [100]:
a[:,:2]     # tum satirlarin ilk iki sutununu secti, ustteki ile ayni islemi yapar

array([[3, 6],
       [7, 1],
       [6, 6],
       [4, 3],
       [4, 9]])

In [101]:
a[1:3,0:2]   # 1den 3 e kadar olan satirlarini secer  :  0dan 2 ye kadar olan satirlarin, 

array([[7, 1],
       [6, 6]])

In [102]:
a = np.random.randint(10, size = (5, 5))  # 0 den 10a kadar  5x5 lik matris olusturur.
a

array([[5, 3, 4, 0, 8],
       [8, 5, 2, 0, 3],
       [4, 2, 7, 5, 5],
       [7, 9, 5, 9, 2],
       [4, 2, 8, 5, 0]])

In [103]:
alt_a = a[0:3,0:2]   # secilen araliklari yeni bir nesne olarak tanimlayabiliriz.

In [104]:
alt_a

array([[5, 3],
       [8, 5],
       [4, 2]])

In [105]:
alt_a[0,0] = 9999  # 0. satir ve 0.sutundaki elemani 9999 yaptik
alt_a[1,1] = 9999   # 1. satir ve 1.sutundaki elemani 9999 yaptik.

In [106]:
alt_a

array([[9999,    3],
       [   8, 9999],
       [   4,    2]])

In [107]:
alt_b = a[0:3,0:2].copy()    # ana verimizde degisiklige sebep olmasin diye .copy() kullanmak cok faydadlidir

In [108]:
alt_b

array([[9999,    3],
       [   8, 9999],
       [   4,    2]])

In [109]:
alt_b[0,0] = 9999
alt_b[1,1] = 9999

In [110]:
a   # ana verimizin degismedigini gorecegiz. ana veri ham haliyle bir yerlerde kalmasi guzel olur. 

array([[9999,    3,    4,    0,    8],
       [   8, 9999,    2,    0,    3],
       [   4,    2,    7,    5,    5],
       [   7,    9,    5,    9,    2],
       [   4,    2,    8,    5,    0]])

## Fancy Index ile Eleman İşlemleri

Sadece belirli indexleri sececeksek bu yontem Fancy Indexleme kullanilir,

In [111]:
v = np.arange(0, 30, 3)  # 0dan 30a kadar 3 er atlayarak array olusturur
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [112]:
v[1]  # 1. indexe ulasir
v[3]  # 3. indexe ulasir

9

In [113]:
[v[1], v[3]]   # 1 ile 3 e ulasir

[3, 9]

In [114]:
### Sadece belirli indexleri sececeksek bu yontem Fancy Indexleme kullanilir,

al_getir = [1,3,5]   # secmek istedigimiz indexler
v[al_getir]         # sectigimiz indexlerin degerleri  bu ikisi beraber kullanilarak index degerleri getirilir.

array([ 3,  9, 15])

In [115]:
m = np.arange(9).reshape((3, 3))   #3x3 matris
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
m[0, [0,2]]   # m deki 0.satiri ve 0 ve 2.sutunlari sectik sadece 0 ve 2. sutunlari aldi. aralik degil!  

array([0, 2])

In [117]:
m[0:,[0,1,2]]   # Tum satirlari aldik   : 1 ve 2. sutundaki 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Koşullu Eleman İşlemleri

!! Ciktilar True ve False doner.

In [118]:
v = np.array([1,2,3,4,5])

In [119]:
v > 3   # v de 3den buyuk olanlari doner, True yada False doner

array([False, False, False,  True,  True])

In [120]:
v < 3   # v de 3den kucuk olanlari doner, True yada False doner.

array([ True,  True, False, False, False])

In [121]:
v <= 3     # v de 3den kucku esit  olanlari doner, True yada False doner

array([ True,  True,  True, False, False])

In [122]:
v == 3   # v de 3'e esit olanlari doner, True yada False doner

array([False, False,  True, False, False])

In [123]:
v != 3    # v de 3 esit olmayanlari doner, True yada False doner

array([ True,  True, False,  True,  True])

In [124]:
(2 * v)  # tum elemanlari 2 ile carpar

array([ 2,  4,  6,  8, 10])

In [125]:
(v ** 2)   # tum elemanlarin karesini alir

array([ 1,  4,  9, 16, 25])

In [126]:
(2 * v) == (v ** 2)  

array([False,  True, False, False, False])

#ufunc yani arkada donusum yaparak bu islemler yapilir

- np.equal
- np.not_equal
- np.less
- np.less_equal
- np.greater
- np.greater_equal

In [127]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [128]:
np.equal(4,v)   # arka tarafta boyle bi fonksiyon calisir. ornek olsun diye yazdik

array([False, False, False,  True, False])

In [129]:
v = np.random.randint(0, 10, (3, 3))
v

array([[6, 4, 3],
       [1, 5, 1],
       [6, 1, 3]])

In [130]:
v > 5   # 5den buyuk olanlari T F doner

array([[ True, False, False],
       [False, False, False],
       [ True, False, False]])

In [131]:
np.sum(v > 5)    # 5den buyuk donen T F larin kac tane True oldugunu toplayip soyler. Yani n kadar True var demek

2

In [132]:
np.sum((v > 3) & (v < 7))     

# 3den buyuk  've'  7 den kucuk kac True var. sadece True lari sayir !!! ( & = and anlamindadir)

4

In [133]:
(v > 3) & (v < 7)      

array([[ True,  True, False],
       [False,  True, False],
       [ True, False, False]])

In [134]:
np.sum((v > 3) | (v < 7))    

# 3den buyuk "veya" 7 den kucuk kac True var. sadece True lari sayar !!! ( | = or anlamindadir )

9

In [135]:
v = np.random.randint(0, 10, (3, 3))
v

array([[8, 4, 3],
       [2, 6, 1],
       [4, 1, 9]])

In [136]:
np.sum(v > 4, axis = 1)      

# sadece satirlardaki 4 den buyuk olanlari doner ve toplar. yani her satirda kac tane bu kosulu saglayan deger var bunun sayisini verir.
# degerin kendisini vermez. 

array([1, 1, 1])

In [137]:
np.sum(v > 4, axis = 0)  

# sadece sutunlarda 4 den buyuk olanlari doner ve toplar. yani her satirda kac tane bu kosulu saglayan deger var bunun sayisini verir.
# degerin kendisini vermez. 

array([1, 1, 1])

In [138]:
np.all(v > 4)  # verideki tum elemanlarin  4 den buyuk olup olmadigini sorgular, hepsi 4 den buyukse TRUE FALSE doner

False

In [139]:
np.all(v > -1)   # verideki tum elemanlarin  4 den buyuk olup olmadigini sorgular, hepsi 4 den buyukse TRUE FALSE doner

True

In [140]:
np.any(v == 4)  

# veride en az bir tane  4 den buyuk eleman olup olup olmadigini sorgular, 
#en az bir tane varsa TRUE FALSE doner

True

In [141]:
np.all(v > 4, axis = 0)    # sadece sutun bazinda 4 den buyuk eleman olup olmadigini sorgular. hepsi 4den buyukse True doner

array([False, False, False])

In [142]:
np.all(v > 4, axis = 1)    # sadece satir bazinda 4 den buyuk eleman olup olmadigini sorgular. hepsi 4den buyukse True doner

array([False, False, False])

# NumPy Hesaplamalı İşlemler

In [143]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [144]:
a - 1   # a daki elemanlarin hepsinden 1 cikarir, 

array([-1,  0,  1,  2,  3])

In [145]:
a / 2   # a daki elemanlarin hepsini 2 ye boler, 

array([0. , 0.5, 1. , 1.5, 2. ])

In [146]:
a * 5   # a daki elemanlarin hepsini 5 ile carpar, 

array([ 0,  5, 10, 15, 20])

In [147]:
a ** 2   # a daki elemanlarin hepsinin karesini alir, 

array([ 0,  1,  4,  9, 16])

In [148]:
a % 2    # a daki elemanlarin hepsinden 2 ye bolumunden kalanlari soyler, 

array([0, 1, 0, 1, 0])

### matematiksel islemleri fonksiyonlarla yapalim

In [149]:
np.add(a,2) #toplama

array([2, 3, 4, 5, 6])

In [150]:
np.subtract(a,1)  #cikarma

array([-1,  0,  1,  2,  3])

In [151]:
np.multiply(a,3)   #carpma

array([ 0,  3,  6,  9, 12])

In [152]:
np.divide(a,3)    # bolme

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [153]:
np.power(a,3)   # karesini alir

array([ 0,  1,  8, 27, 64])

In [154]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [155]:
np.add.reduce(a)   # tum degerleri birbiri ile toplar sum dan farki?

15

In [156]:
np.sum(a)

15

In [157]:
np.add.accumulate(a)   

# tum degerleri birbiri ile toplar asamalari da gosterir. carma bolme ve digerleri icinde ayni islemler yapilabilir

array([ 1,  3,  6, 10, 15])

In [158]:
a = np.random.normal(5, 10, 30)
a

array([ 11.94021547, -11.77093636,  -3.76655309,   6.82536532,
        15.57692134,  12.12393891,  22.76648343,  12.95685414,
        14.80376432,   2.91820563,   4.85903762,  12.53091849,
        23.54076382,  15.39995084,   1.39253017,  -1.1440338 ,
       -21.49939276, -14.21236957,   1.85754465,   0.80781352,
        37.83786659,  19.97340547,  -0.65439759,  -3.13303454,
         5.53126978,  15.72813798, -13.03775721,  15.58050347,
       -14.97540787,  14.03169619])

In [159]:
np.mean(a)   # a nin ortalamasini verir

6.159643479898899

In [160]:
np.std(a)   # a nin standart sapmasini verir

13.0427733817622

In [161]:
np.var(a)   # a nin varyansini verir

170.11393748800455

In [162]:
np.median(a)  # a nin median degerini verir. en orta deger

6.178317550111286

In [163]:
sum(a)  # normal sekilde toplama yaptik

184.78930439696694

In [164]:
np.min(a)   # en kucuk deger tek boyutlu

-21.49939275753372

In [165]:
np.max(a) # en buyuk deger tek boyutlu

37.83786659269721

In [166]:
a = np.random.normal(0, 1, (3,3))
a

array([[ 1.17298477,  2.12990797, -0.76391553],
       [ 1.38192669,  0.43308211,  0.8101313 ],
       [-0.43581283, -0.1697933 ,  0.03907255]])

In [167]:
a.sum()   # a yi toplar

4.5975837219854565

In [168]:
a.sum(axis = 1)   # satir bazinda toplama yapar

array([ 2.53897721,  2.62514009, -0.56653358])

In [169]:
a.sum(axis = 0)   # sutun bazinda toplama yapar

array([2.11909862, 2.39319679, 0.08528831])

# Pandas Series
- Pandas serileri kolon(değişken) ismi almayan ve indexlenen veriler barındırır.
- Pandas seriler tek boyutludur

### Pandas Seri Oluşturma Yöntemleri

In [170]:
import numpy as np
import pandas as pd

In [171]:
seri1 = pd.Series([10,20,30,40])  
seri1

0    10
1    20
2    30
3    40
dtype: int64

In [172]:
seri2 = pd.Series(["Ahmet","Mehmet",3, 4.6, None, " "])  # farkli veri tiplrerini barindirabilir. 
seri2

0     Ahmet
1    Mehmet
2         3
3       4.6
4      None
5          
dtype: object

In [173]:
seri3 = pd.Series([1,5,0.9,34],index = (1,3,5,7))    
seri3

1     1.0
3     5.0
5     0.9
7    34.0
dtype: float64

In [174]:
seri4 = pd.Series([1,5,0.9,34], index = ('a','a','a','d'))    # str olarak da index belirleyebiliriz
seri4

a     1.0
a     5.0
a     0.9
d    34.0
dtype: float64

In [175]:
sozluk = { "ahmet" : 1000, "mehmet" : 2500, "ayse" : 4500}    #sozluk uzerinden index atayacagiz.
sozluk

{'ahmet': 1000, 'ayse': 4500, 'mehmet': 2500}

In [176]:
seri5 = pd.Series(sozluk)  #sozlugu seriye cevirdik
seri5

ahmet     1000
mehmet    2500
ayse      4500
dtype: int64

In [177]:
npa = np.array([1,2,3,566,88])     # array ile seri olusturduk
npa

array([  1,   2,   3, 566,  88])

In [178]:
seri6 = pd.Series(npa)    #arrayi pandas serisine cevirdik
seri6

0      1
1      2
2      3
3    566
4     88
dtype: int64

#### type, data type, index, shape sorgulama

In [179]:
seri6

0      1
1      2
2      3
3    566
4     88
dtype: int64

In [180]:
type(seri6)

pandas.core.series.Series

In [181]:
seri5

ahmet     1000
mehmet    2500
ayse      4500
dtype: int64

In [182]:
seri5.axes    #index hakkinda bilgi  verir

[Index(['ahmet', 'mehmet', 'ayse'], dtype='object')]

In [183]:
seri5.index #index hakkinda bilgi  verir axes ile ayni isi yapar

Index(['ahmet', 'mehmet', 'ayse'], dtype='object')

In [184]:
seri2

0     Ahmet
1    Mehmet
2         3
3       4.6
4      None
5          
dtype: object

In [185]:
seri2.dtype   #veri tipi hakkinda bilgi verir

dtype('O')

In [186]:
seri5.dtype 

dtype('int64')

#### serideki verilere erişim

In [187]:
seri = pd.Series([1,5,0.9,34], index = ('a','b','c','d'))
seri

a     1.0
b     5.0
c     0.9
d    34.0
dtype: float64

In [188]:
seri["c"],seri[3]   #index ismi ile veya sıra numarası ile veriye erişim

(0.9, 34.0)

In [189]:
seri[["a","c"]]  # a ve c indisli verilere ulaşır. İç içe köşeli parantezlere dikkat.

a    1.0
c    0.9
dtype: float64

In [190]:
seri["a":"c"]  # belli bir aralıkdaki verilere erişim

a    1.0
b    5.0
c    0.9
dtype: float64

In [191]:
seri[0:3]

a    1.0
b    5.0
c    0.9
dtype: float64

In [192]:
seri

a     1.0
b     5.0
c     0.9
d    34.0
dtype: float64

In [193]:
seri[(seri > 1) & (seri < 10)] # 1'den büyük 10'dan küçük verilere erişim

b    5.0
dtype: float64

In [194]:
(seri > 1) & (seri < 10)

a    False
b     True
c    False
d    False
dtype: bool

#### index, keys, values, items ile verilere erişim 

In [195]:
seri = pd.Series([1,5,0.9,34], index = ('a','b','c','d'))    # str olarakda index belirleyebiliriz
seri

a     1.0
b     5.0
c     0.9
d    34.0
dtype: float64

In [196]:
print(seri.index, seri.keys, seri.values,seri.items, sep='\n\n*************************\n')

Index(['a', 'b', 'c', 'd'], dtype='object')

*************************
<bound method Series.keys of a     1.0
b     5.0
c     0.9
d    34.0
dtype: float64>

*************************
[ 1.   5.   0.9 34. ]

*************************
<bound method Series.items of a     1.0
b     5.0
c     0.9
d    34.0
dtype: float64>


#### sorgulama yapma ve değer atama

In [197]:
seri = pd.Series([1,5,0.9,34], index = ('a','b','c','d'))    # str olarakda index belirleyebiliriz
seri

a     1.0
b     5.0
c     0.9
d    34.0
dtype: float64

In [198]:
'a' in seri,'e' in seri

(True, False)

In [199]:
seri['b']=500
seri

a      1.0
b    500.0
c      0.9
d     34.0
dtype: float64

## Concat ile birlestirme

In [200]:
seri = pd.Series([1,5,0.9,34], index = ('a','b','c','d'))    
seri

a     1.0
b     5.0
c     0.9
d    34.0
dtype: float64

In [201]:
seri = pd.concat([seri, seri, seri], ignore_index=True) 
#serileri birlestirir. concat ile birlestirme
seri

0      1.0
1      5.0
2      0.9
3     34.0
4      1.0
5      5.0
6      0.9
7     34.0
8      1.0
9      5.0
10     0.9
11    34.0
dtype: float64

In [202]:
seri.append(seri, ignore_index=True)    #append ile birlestirme de yapilabilir

0      1.0
1      5.0
2      0.9
3     34.0
4      1.0
5      5.0
6      0.9
7     34.0
8      1.0
9      5.0
10     0.9
11    34.0
12     1.0
13     5.0
14     0.9
15    34.0
16     1.0
17     5.0
18     0.9
19    34.0
20     1.0
21     5.0
22     0.9
23    34.0
dtype: float64

## loc ve iloc
Yukarıda anlatılan veriye erişim yöntemleri ile bazı sorunlar yaşandığınan loc ve iloc metoduna ihtiyaç duyulmaktadır.

In [203]:
seri = pd.Series(['a','b','c','d','e'], index = (1,2,3,4,5))    
seri

1    a
2    b
3    c
4    d
5    e
dtype: object

In [205]:
# seri[0] 
# sıfır indisli veri olamdığından hata olacaktır

In [206]:
seri[1] 

'a'

In [207]:
# fakat kodu aşağıdaki gibi yazarsak bu defa da 1 indisli veri elde edilemeyecektir
seri[1:3]

2    b
3    c
dtype: object

In [208]:
seri[0:3]

1    a
2    b
3    c
dtype: object

In [209]:
seri = pd.Series([1,5,0.9,34], index = ('a','b','c','d'))   
seri

a     1.0
b     5.0
c     0.9
d    34.0
dtype: float64

Bu nedenle loc ve iloc metodlarına ihtiyaç duyulmaktadır

In [210]:
seri.loc['a':'c'] # loc labelseri based indexing, index ismi ile veriye erişim

a    1.0
b    5.0
c    0.9
dtype: float64

In [211]:
seri.iloc[0:3] # iloc positional indexing, sıra numarasına göre veriye erişim

a    1.0
b    5.0
c    0.9
dtype: float64